"""
Code generator for Javascript.
"""

from __future__ import absolute_import, division, print_function, unicode_literals

import argparse

from babelapi.data_type import (
    is_user_defined_type,
    unwrap,
)
from babelapi.generator import CodeGeneratorMonolingual
from babelapi.lang.js import JavascriptTargetLanguage


_cmdline_parser = argparse.ArgumentParser(prog='js-generator')
_cmdline_parser.add_argument(
    'filename',
    help=('The name to give the single Javascript file that is created and '
          'contains all of the routes.'),
)
_cmdline_parser.add_argument(
    '-a',
    '--route-attribute',
    action='append',
    type=str,
    default=[],
    help='Route attribute to include in the invocation of self.request.',
)


class JavascriptGenerator(CodeGeneratorMonolingual):
    """Generates a single Javascript file with all of the routes defined."""

    lang = JavascriptTargetLanguage()
    cmdline_parser = _cmdline_parser

    # Instance var of the current namespace being generated
    cur_namespace = None

    preserve_aliases = True

    def generate(self, api):
        with self.output_to_relative_path(self.args.filename):

            self.emit('// Auto-generated by BabelAPI, do not modify.')
            self.emit('var routes = {};')

            for namespace in api.namespaces.values():
                for route in namespace.routes:
                    self._generate_route(namespace, route)

            self.emit()
            self.emit('module.exports = routes')

    def _generate_route(self, namespace, route):
        function_name = self.lang.format_method(namespace.name + '_' + route.name)
        self.emit()
        self.emit('/**')
        if route.doc:
            self.emit_wrapped_text(self.process_doc(route.doc, self._docf), prefix=' * ')
        if route.deprecated:
            self.emit(' * @deprecated')

        self.emit(' * @arg {%s} arg - The request parameters.' %
                  self.lang.format_type(route.arg_data_type))
        if is_user_defined_type(route.arg_data_type):
            for field in route.arg_data_type.all_fields:
                field_doc = ' - ' + field.doc if field.doc else ''
                field_type, nullable, _ = unwrap(field.data_type)
                field_js_type = self.lang.format_type(field_type)
                if nullable:
                    field_js_type += '|null'
                self.emit_wrapped_text(
                    '@arg {%s} arg.%s%s' %
                        (field_js_type, field.name,
                         self.process_doc(field_doc, self._docf)),
                    prefix=' * ')
        self.emit(' * @returns {%s}' % self.lang.format_type(route.result_data_type))
        self.emit(' */')
        self.emit('routes.%s = function (arg) {' % function_name)
        with self.indent():
            url = '{}/{}'.format(namespace.name, route.name)
            if self.args.route_attribute:
                additional_args = []
                for attr in self.args.route_attribute:
                    additional_args.append(self.lang.format_obj(route.attrs.get(attr)))
                self.emit(
                    'return self.request("{}", arg, {});'.format(
                        url, ', '.join(additional_args)))
            else:
                self.emit(
                    'return self.request("%s", arg);' % url)
        self.emit('}')

    def _docf(self, tag, val):
        """
        Callback used as the handler argument to process_docs(). This converts
        Babel doc references to JSDoc-friendly annotations.
        """
        # TODO(kelkabany): We're currently just dropping all doc ref tags.
        return val
