language: node_js
node_js:
  - 'node'
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
  - '7'
  - '6'
git:
  submodules: false
before_install:
  - npm install -g npm@latest
script: npm run size
